#! /bin/bash

note="$1"
time="$2"
    
period="$(perl -e"printf'%.0f',600000/440/2**(($note-69)/12)")"
gpio -g mode 18 pwm
gpio pwmr "$((period))"
gpio -g pwm 18 "$((period/2))"
gpio pwm-ms

sleep "$time"

gpio -g mode 18 in
